spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Abhishek028_


notification :
  serviceName: sms

mail:
  host: imabhishek028
  port: 5617



